import { test, expect, type Page } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';

async function example(page: Page, scenario = 'stale') {
  await page.goto('/#/evidence');
  await page.getByRole('combobox', { name: 'Start with a real question' }).selectOption(scenario);
  await page.getByRole('button', { name: 'Try local example', exact: true }).click();
  await page.getByRole('button', { name: 'Allow local evidence', exact: true }).click();
  await expect(page.locator('.finding-card')).toBeVisible();
}
async function axe(page: Page) {
  const result = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze();
  expect(result.violations.map(item => ({ id: item.id, description: item.description,
    nodes: item.nodes.map(node => ({ target: node.target, summary: node.failureSummary })) }))).toEqual([]);
}
test('appearance is distinct, persistent, keyboard-accessible and available in both themes', async ({ page }, testInfo) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await expect(page.getByRole('heading', { name: 'Every run has a story.' })).toBeVisible();
  await axe(page);
  await page.getByRole('button', { name: 'Customize appearance' }).click();
  await expect(page.getByRole('dialog', { name: 'Your workbench, your way' })).toBeVisible();
  await page.getByRole('radio', { name: 'Graphite', exact: true }).check();
  await page.getByRole('radio', { name: 'Teal', exact: true }).check();
  await page.getByRole('combobox', { name: 'Spacing', exact: true }).selectOption('compact');
  await page.getByRole('combobox', { name: 'Text size', exact: true }).selectOption('large');
  await page.getByRole('combobox', { name: 'Motion', exact: true }).selectOption('reduced');
  await axe(page);
  await page.getByRole('button', { name: 'Done', exact: true }).click();
  await page.reload();
  await expect(page.locator('html')).toHaveAttribute('data-theme', 'graphite');
  await expect(page.locator('html')).toHaveAttribute('data-accent', 'teal');
  await expect(page.locator('html')).toHaveAttribute('data-density', 'compact');
  await expect(page.locator('html')).toHaveAttribute('data-text-size', 'large');
  await page.keyboard.press('Control+k');
  await expect(page.getByRole('dialog', { name: 'Where next?' })).toBeVisible();
  await page.getByRole('searchbox', { name: 'Find a page' }).fill('evidence');
  await page.getByRole('navigation', { name: 'Quick navigation' }).getByRole('link', { name: /Evidence Lens/ }).click();
  await expect(page).toHaveURL(/#\/evidence/);
  await expect(page.getByRole('heading', { name: /Does the proof still apply/ })).toBeVisible();
  await axe(page);
  await page.screenshot({ path: testInfo.outputPath('evidence-graphite-empty.png'), fullPage: true });
  expect(errors).toEqual([]);
});
test('evidence review, read-only playback, manifest, reviewed correction/export and recovery work together', async ({ page }, testInfo) => {
  const errors: string[] = []; page.on('pageerror', error => errors.push(error.message));
  await example(page);
  await expect(page.locator('.finding-card').getByText('Unverifiable', { exact: true })).toBeVisible();
  await expect(page.getByText('A fresh check is needed.', { exact: true })).toBeVisible();
  await axe(page);
  await page.screenshot({ path: testInfo.outputPath('evidence-paper-review.png'), fullPage: true });
  let writes = 0;
  const listener = (request: { method(): string }) => { if (request.method() === 'POST') writes++; };
  page.on('request', listener);
  await page.getByRole('button', { name: 'See the result', exact: false }).click();
  await expect(page.getByRole('tab', { name: 'Timeline', exact: true })).toHaveAttribute('aria-selected', 'true');
  await expect(page.getByRole('slider', { name: 'Timeline position' })).toHaveValue('3');
  await page.getByText('Inspect actual result', { exact: true }).click();
  await expect(page.locator('.evidence-inspector .json-block').filter({ hasText: '"passed": 3' })).toBeVisible();
  await page.getByRole('button', { name: 'Reset', exact: true }).click();
  await page.getByRole('button', { name: 'Play timeline', exact: true }).click();
  await expect(page.getByRole('slider', { name: 'Timeline position' })).toHaveValue('5');
  await expect(page.getByRole('button', { name: 'Play timeline', exact: true })).toBeVisible();
  expect(writes).toBe(0);
  page.off('request', listener);
  await page.getByRole('tab', { name: 'Manifest', exact: true }).click();
  await expect(page.getByRole('row').filter({ hasText: 'Mock health observations only' })).toContainText('Not observed');
  await expect(page.getByRole('row').filter({ hasText: 'In-memory unit assertions' })).toContainText('linked steps');
  await axe(page);
  await page.getByRole('tab', { name: 'Review', exact: true }).click();
  await page.getByRole('button', { name: 'Draft a clearer claim', exact: true }).click();
  await expect(page.getByRole('dialog', { name: 'Review a clearer claim' })).toContainText('does not establish');
  await page.getByRole('button', { name: 'Save reviewed draft', exact: true }).click();
  await page.getByRole('tab', { name: 'Handoff', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Reviewed claim correction', exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Review handoff export', exact: true }).click();
  await expect(page.getByRole('dialog', { name: 'Review this plaintext export' })).toContainText('Unverifiable');
  const download = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Download reviewed file', exact: true }).click();
  expect((await download).suggestedFilename()).toMatch(/\.md$/);
  await page.getByRole('tab', { name: 'Recovery', exact: true }).click();
  await page.getByRole('button', { name: 'Review recovery plan', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Actual restart boundary', exact: true })).toBeVisible();
  await expect(page.locator('.recovery-plan')).toContainText('Event 2');
  await expect(page.locator('.recovery-plan')).toContainText('0 external writes');
  const executed = page.waitForResponse(response => response.url().endsWith('/api/lens/recovery/execute'));
  await page.getByRole('button', { name: 'Approve this plan & create new run', exact: true }).click();
  const corrected = await (await executed).json();
  expect(corrected.assessment.counts.Supported).toBe(1);
  expect(corrected.comparison.linked).toBe(true);
  await page.getByRole('tab', { name: 'Compare', exact: true }).click();
  await expect(page.getByRole('row').filter({ hasText: 'The final change passes the unit tests.' })).toContainText('Unverifiable');
  await expect(page.getByRole('row').filter({ hasText: 'The final change passes the unit tests.' })).toContainText('Supported');
  await page.screenshot({ path: testInfo.outputPath('evidence-recovery-comparison.png'), fullPage: true });
  await page.locator('.lens-recording').filter({ hasText: 'The code changed after the test' }).click();
  await page.getByRole('tab', { name: 'Review', exact: true }).click();
  await expect(page.locator('.finding-card').getByText('Unverifiable', { exact: true })).toBeVisible();
  await page.getByRole('navigation', { name: 'Primary' }).getByRole('link', { name: 'Recordings', exact: true }).click();
  await page.getByRole('navigation', { name: 'Primary' }).getByRole('link', { name: 'Evidence Lens', exact: true }).click();
  await expect(page.locator('.lens-recording')).toHaveCount(2);
  expect(errors).toEqual([]);
});
test('scope mismatch and denied queries are not service failures; mobile and privacy remain usable', async ({ page }, testInfo) => {
  await example(page, 'scope');
  await expect(page.locator('.finding-card')).toContainText('Unverifiable');
  await expect(page.locator('.finding-card')).toContainText('resourceId differs');
  await page.getByRole('combobox', { name: 'Start with a real question' }).selectOption('denied');
  await page.getByRole('button', { name: 'Try local example', exact: true }).click();
  await expect(page.locator('.finding-card')).toContainText('denied');
  await expect(page.locator('.finding-card')).not.toContainText('Contradicted');
  await page.getByRole('tab', { name: 'Privacy', exact: true }).click();
  await expect(page.getByText('copilot-private-panels', { exact: true })).toBeVisible();
  await expect(page.getByText('cli-agency-resume', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'Change privacy choices', exact: true }).click();
  await page.getByRole('checkbox', { name: /Include supplied content/ }).check();
  await page.getByRole('combobox', { name: 'Keep records for', exact: true }).selectOption('7');
  await page.getByRole('button', { name: 'Save privacy choices', exact: true }).click();
  await expect(page.getByText('Included with imports', { exact: true })).toBeVisible();
  await expect(page.getByText('7 days, reviewed removal', { exact: true })).toBeVisible();
  await page.setViewportSize({ width: 390, height: 844 });
  await axe(page);
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth + 2)).toBe(true);
  await page.getByRole('tab', { name: 'Review', exact: true }).click();
  await page.screenshot({ path: testInfo.outputPath('evidence-mobile.png'), fullPage: true });
  await page.getByRole('tab', { name: 'Review', exact: true }).focus();
  await page.keyboard.press('ArrowRight');
  await expect(page.getByRole('tab', { name: 'Timeline', exact: true })).toBeFocused();
  await expect(page.getByRole('tab', { name: 'Timeline', exact: true })).toHaveAttribute('aria-selected', 'true');
});
test('external preview can be cancelled and a failed live request never looks like a successful demo', async ({ page }) => {
  await example(page);
  let modelRequests = 0;
  page.on('request', request => { if (request.url().endsWith('/api/lens/live-demo')) modelRequests++; });
  await page.getByRole('button', { name: 'Use live Azure', exact: true }).click();
  await expect(page.getByRole('dialog', { name: 'Review the live Azure request' })).toContainText('synthetic');
  await page.getByRole('button', { name: 'Cancel', exact: true }).click();
  expect(modelRequests).toBe(0);
  await page.getByRole('button', { name: 'Use live Azure', exact: true }).click();
  await page.getByRole('button', { name: 'Approve & run live Azure', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('FOUNDRY_NOT_CONFIGURED');
  expect(modelRequests).toBe(1);
  await expect(page.locator('.lens-recording')).toHaveCount(1);
  await expect(page.locator('.finding-card')).toContainText('Unverifiable');
});
