import { mkdir, writeFile } from 'node:fs/promises';
import { setTimeout as delay } from 'node:timers/promises';
import { loadLocalEnvironment } from '../server/environment.mjs';
loadLocalEnvironment();

const base = process.env.AFR_URL ?? 'http://127.0.0.1:4180';
async function api(path, body) {
  const response = await fetch(`${base}${path}`, body === undefined ? {} : {
    method: 'POST', headers: { 'Content-Type': 'application/json', 'X-AFR-Client': 'ui' }, body: JSON.stringify(body),
  });
  const value = await response.json();
  if (!response.ok) throw new Error(`${response.status}: ${JSON.stringify(value)}`);
  return value;
}
async function settled(id) {
  for (let attempt = 0; attempt < 100; attempt++) {
    const detail = await api(`/api/runs/${id}`);
    if (detail.run.status !== 'running') return detail;
    await delay(50);
  }
  throw new Error(`The sandbox run did not settle within five seconds: ${id}`);
}
const titles = {
  success: 'Sales report - clean baseline',
  retry: 'Sales report - transient failure recovered',
  blocked: 'Board report - restricted read blocked',
  failure: 'Report parser - persistent failure',
  approval: 'Sales report - awaiting your approval',
};
const listed = await api('/api/runs');
const recordings = [];
const expected = { success: 'completed', retry: 'completed', blocked: 'blocked', failure: 'failed', approval: 'awaiting_approval' };
for (const [scenarioId, name] of Object.entries(titles)) {
  const existing = listed.runs.find(run => run.origin === 'demo' && run.name === name &&
    run.status === expected[scenarioId]);
  const id = existing?.id ?? (await api('/api/demos', { scenarioId, name })).runId;
  const detail = await settled(id);
  if (!detail.integrity.valid) throw new Error(`Inconsistent recording: ${id}`);
  if (detail.run.status !== expected[scenarioId]) throw new Error(`Scenario ${scenarioId} ended as ${detail.run.status}, expected ${expected[scenarioId]}. Inspect run ${id}.`);
  recordings.push({ id, name, scenarioId, status: detail.run.status, events: detail.run.eventCount,
    metrics: detail.run.metrics, view: `${base}/#/runs/${id}` });
}
const failure = recordings.find(run => run.scenarioId === 'failure');
const existingFork = listed.runs.find(run => run.origin === 'demo' && run.parentRunId === failure.id && run.scenarioId === 'success' && run.status === 'completed');
const fixedId = existingFork?.id ?? (await api(`/api/runs/${failure.id}/fork`, { scenarioId: 'success', name: 'What-if - replace the malformed fixture' })).runId;
if ((await settled(fixedId)).run.status !== 'completed') throw new Error('The clean what-if rerun did not complete.');
const comparison = await api(`/api/runs/${failure.id}/compare/${fixedId}`);
const priorApproved = listed.runs.find(run => run.name === 'Sales report - approved sandbox action' && run.origin === 'demo' && run.status === 'completed');
let approvedId = priorApproved?.id;
if (!approvedId) {
  approvedId = (await api('/api/demos', { scenarioId: 'approval', name: 'Sales report - approved sandbox action' })).runId;
  const pending = await settled(approvedId);
  await api(`/api/approvals/${pending.approvals[0].id}/resolve`, {
    decision: 'approve', actor: 'Demo preparation script', comment: 'Explicitly approve this separate fictional sandbox example. The live presentation example remains pending.',
  });
  await settled(approvedId);
}
const approved = await api(`/api/runs/${approvedId}`);
if (approved.run.status !== 'completed' || approved.deliveries.length !== 1) throw new Error('The approved sandbox example did not complete exactly once.');
await mkdir(new URL('../artifacts/', import.meta.url), { recursive: true });
for (const format of ['json', 'markdown', 'otlp']) {
  const response = await fetch(`${base}/api/runs/${approvedId}/export?format=${format}`);
  if (!response.ok) throw new Error(`Export failed: ${response.status}`);
  const filename = format === 'markdown' ? 'approved-flight-report.md' : format === 'otlp' ? 'approved-flight-otlp.json' : 'approved-flight-recording.json';
  await writeFile(new URL(`../artifacts/${filename}`, import.meta.url), await response.text(), 'utf8');
}
const manifest = { preparedAt: new Date().toISOString(), baseUrl: base, recordings, approvedRunId: approvedId, comparison,
  note: 'All rows were generated by actual local sandbox execution. The presentation approval remains pending. No email was sent.' };
await writeFile(new URL('../artifacts/demo-workspace.json', import.meta.url), JSON.stringify(manifest, null, 2), 'utf8');
console.log(JSON.stringify({ prepared: recordings.length + 2, pendingApprovalRunId: recordings.find(run => run.scenarioId === 'approval').id,
  approvedRunId: approvedId, recoveredForkRunId: fixedId, comparisonDelta: comparison.delta, saved: 'artifacts\\demo-workspace.json' }, null, 2));
